name: Get JSON file from scrapper

on:
  schedule:
    - cron:  '*/5 * * * *'
      #00 10 * * *

jobs:
  getJson:
    runs-on: ubuntu-latest
    steps:
        - uses: suisei-cn/actions-download-file@v1
          id: jsonContent
          name: Download the file
          with:
            url: "https://cache1.phantombooster.com/plBOJLwVHsA/0dssBQ5XSfnRTJ53UMdTUw/results.json"
            target: assets/posts.json
