name: Get JSON file from scrapper

on:
  schedule:
    - cron:  '00 10 * * *'

jobs:
  getJson:
    runs-on: ubuntu-latest
    steps:
        - uses: suisei-cn/actions-download-file@v1
          name: instagramHashtagScraperResults
          with:
            url: "https://cache1.phantombooster.com/plBOJLwVHsA/0dssBQ5XSfnRTJ53UMdTUw/results.json"
            target: assets/
          run: echo "All ran successfully"




# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Greet
      run: echo "Hello ${{ github.event.inputs.name }}"
