name: Get JSON file from scrapper

# Scheduler to run action ones a day @ 10am (currently every 5 mins for testing)
# on:
#   schedule:
#    - cron:  '*/5 * * * *'
#       #00 10 * * *

# Manually trigger the action 
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Contributor'
        # Default value if no value is explicitly provided
        default: 'name'
        # Input has to be provided for the workflow to run
        required: true

# All jobs the action makes
jobs:
  getJson:
    runs-on: ubuntu-latest
    steps:

      #Get contents from url and write then to file in repo (WOKRING)
        - uses: suisei-cn/actions-download-file@v1
          id: jsonContent
          name: Download the file
          with:
            url: "https://cache1.phantombooster.com/plBOJLwVHsA/0dssBQ5XSfnRTJ53UMdTUw/results.json"
            target: assets/posts.json

      # Check contents of posts.json file
        - name: Read package.json
          id: package
          uses: juliangruber/read-file-action@v1
          with:
            path: assets/posts.json

        - name: Echo package.json
          run: echo ${{ steps.package.outputs.content }}
          
        - name: Display structure of downloaded files
          run: ls -R
      
      # Commit chnages to repo
        - name: Git Auto Commit
          uses: stefanzweifel/git-auto-commit-action@v4.8.0
