name: Get JSON file from scrapper

# on:
#   schedule:
#    - cron:  '*/5 * * * *'
#       #00 10 * * *
      
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Contributor'
        # Default value if no value is explicitly provided
        default: 'name'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  getJson:
    runs-on: ubuntu-latest
    steps:
       # - uses: suisei-cn/actions-download-file@v1
        - uses: actions/checkout@v2       
          id: jsonContent
          name: Download the file
          with:
            url: "https://cache1.phantombooster.com/plBOJLwVHsA/0dssBQ5XSfnRTJ53UMdTUw/results.json"
            target: assets/posts.json
        - name: check for changes and commit
          run: |
            git status
            git add .
            git commit -m "Auto updating posts.json"
            git fetch origin master
            git push origin HEAD:master
