name: Get JSON file from scrapper

# Scheduler to run action ones a day @ 10am (currently every 5 mins for testing)
on:
#   schedule:
#    - cron:  '45 20 * * *'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

# All jobs the action makes
jobs:
  getJson:
    runs-on: ubuntu-latest
    steps:

      # Checkout current branch / repo?
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.head_ref }}

      #Get contents from url and write then to file in repo (WOKRING)
        - uses: suisei-cn/actions-download-file@v1
          id: jsonContent
          name: Download the file
          with:
            url: "https://cache1.phantombooster.com/plBOJLwVHsA/0dssBQ5XSfnRTJ53UMdTUw/results.json"
            target: assets/
              
      # Commit chnages to repo
        - name: Git Auto Commit
          uses: stefanzweifel/git-auto-commit-action@v4.8.0
          with:
            commit_message: Auto commit instagram scrapper json file
